### ISSUE TITLE
Unable to compile FakeSign

### ISSUE THREAD

**Issue by SirCmpwn** [mono/roslyn#11]
sircmpwn@makase ~/s/roslyn master> xbuild Src/Tools/Source/FakeSign/FakeSign.csproj
    XBuild Engine Version 12.0
    Mono, Version 3.12.0.0
    Copyright (C) 2005-2013 Various Mono authors

    Build started 2/4/2015 3:13:55 PM.
    __________________________________________________
    Project "/home/sircmpwn/sources/roslyn/Src/Tools/Source/FakeSign/FakeSign.csproj" (default target(s)):
    /home/sircmpwn/sources/roslyn/Src/Tools/Source/FakeSign/FakeSign.csproj:  warning : Project has unknown ToolsVersion '14.0'. Using the default tools version '2.0' instead.
        Target PrepareForBuild:
            Configuration: Debug Platform: AnyCPU
        Target GetFrameworkPaths:
    /usr/lib/mono/2.0/Microsoft.Common.targets:  warning : TargetFrameworkVersion 'v4.5' not supported by this toolset (ToolsVersion: 2.0).
        Target GenerateSatelliteAssemblies:
        No input files were specified for target GenerateSatelliteAssemblies, skipping.
        Target GenerateSyntaxModel:
        No output files were specified for target GenerateSyntaxModel, skipping.
        Target GenerateSyntaxModelTests:
        No output files were specified for target GenerateSyntaxModelTests, skipping.
        Target GenerateBoundTree:
        No output files were specified for target GenerateBoundTree, skipping.
        Target GenerateErrorFacts:
        No output files were specified for target GenerateErrorFacts, skipping.
        Target GenerateAssemblyInfoFile:
    : error : Error initializing task WriteCodeFragment: Not registered task WriteCodeFragment.
            Build FAILED.
            Warnings:
            /home/sircmpwn/sources/roslyn/Src/Tools/Source/FakeSign/FakeSign.csproj (default targets) ->
                /home/sircmpwn/sources/roslyn/Src/Tools/Source/FakeSign/FakeSign.csproj:  warning : Project has unknown ToolsVersion '14.0'. Using the default tools version '2.0' instead.
            /home/sircmpwn/sources/roslyn/Src/Tools/Source/FakeSign/FakeSign.csproj (default targets) ->
            /usr/lib/mono/2.0/Microsoft.Common.targets (GetFrameworkPaths target) ->
                /usr/lib/mono/2.0/Microsoft.Common.targets:  warning : TargetFrameworkVersion 'v4.5' not supported by this toolset (ToolsVersion: 2.0).
            Errors:
            /home/sircmpwn/sources/roslyn/Src/Tools/Source/FakeSign/FakeSign.csproj (default targets) ->
            /home/sircmpwn/sources/roslyn/Src/Tools/Microsoft.CodeAnalysis.Toolset.Open/Targets/GenerateAssemblyInfo.targets (GenerateAssemblyInfoFile target) ->
                : error : Error initializing task WriteCodeFragment: Not registered task WriteCodeFragment.
                 2 Warning(s)
                 1 Error(s)
            Time Elapsed 00:00:00.1682610

I installed the MS PCL here:

    sircmpwn@makase ~/s/roslyn master> ls /usr/lib/mono/xbuild-frameworks/.NETPortable/v4.5/Profile/Profile7
    GlobalDTARSettings.proj*                    System.dll*                         System.Reflection.dll*                              System.ServiceModel.NetTcp.dll*
    Microsoft.CSharp.dll*                       System.Dynamic.Runtime.dll*         System.Reflection.Extensions.dll*                   System.ServiceModel.Primitives.dll*
    Microsoft.VisualBasic.dll*                  System.Globalization.dll*           System.Reflection.Primitives.dll*                   System.ServiceModel.Security.dll*
    mscorlib.dll*                               System.IO.Compression.dll*          System.Resources.ResourceManager.dll*               System.ServiceModel.Web.dll*
    RedistList/                                 System.IO.dll*                      System.Runtime.dll*                                 System.Text.Encoding.dll*
    SupportedFrameworks/                        System.Linq.dll*                    System.Runtime.Extensions.dll*                      System.Text.Encoding.Extensions.dll*
    System.Collections.Concurrent.dll*          System.Linq.Expressions.dll*        System.Runtime.InteropServices.dll*                 System.Text.RegularExpressions.dll*
    System.Collections.dll*                     System.Linq.Parallel.dll*           System.Runtime.InteropServices.WindowsRuntime.dll*  System.Threading.dll*
    System.ComponentModel.Annotations.dll*      System.Linq.Queryable.dll*          System.Runtime.Numerics.dll*                        System.Threading.Tasks.dll*
    System.ComponentModel.DataAnnotations.dll*  System.Net.dll*                     System.Runtime.Serialization.dll*                   System.Threading.Tasks.Parallel.dll*
    System.ComponentModel.dll*                  System.Net.Http.dll*                System.Runtime.Serialization.Json.dll*              System.Windows.dll*
    System.ComponentModel.EventBasedAsync.dll*  System.Net.NetworkInformation.dll*  System.Runtime.Serialization.Primitives.dll*        System.Xml.dll*
    System.Core.dll*                            System.Net.Primitives.dll*          System.Runtime.Serialization.Xml.dll*               System.Xml.Linq.dll*
    System.Diagnostics.Contracts.dll*           System.Net.Requests.dll*            System.Security.Principal.dll*                      System.Xml.ReaderWriter.dll*
    System.Diagnostics.Debug.dll*               System.Numerics.dll*                System.ServiceModel.dll*                            System.Xml.Serialization.dll*
    System.Diagnostics.Tools.dll*               System.ObjectModel.dll*             System.ServiceModel.Duplex.dll*                     System.Xml.XDocument.dll*
    System.Diagnostics.Tracing.dll*             System.Reflection.Context.dll*      System.ServiceModel.Http.dll*                       System.Xml.XmlSerializer.dll*

**Comment by marek-safar** [comment]
You need to use master mono as described in README

**Comment by SirCmpwn** [comment]
I am using master mono, that's not the problem here.

**Comment by marek-safar** [comment]
You are using Mono, Version 3.12.0.0 not master

**Comment by SirCmpwn** [comment]
Yeah, you're right. I compiled it incorrectly.
