### ISSUE TITLE
StyleCop errors during CSharpWorkspace build

### ISSUE THREAD

**Issue by SirCmpwn** [mono/roslyn#12]
Here's the full build: http://ix.io/gaC

The important bit:

	Errors:
	/home/sircmpwn/sources/roslyn/Src/Workspaces/CSharp/Portable/CSharpWorkspace.csproj (default targets) ->
	/usr/lib/mono/4.5/Microsoft.Common.targets (ResolveProjectReferences target) ->
	/home/sircmpwn/sources/roslyn/Src/Workspaces/Core/Portable/Workspaces.csproj (default targets) ->
	/home/sircmpwn/sources/roslyn/packages/StyleCop.MSBuild.4.7.48.2/build/StyleCop.MSBuild.Targets (StyleCop target) ->
		: error : Error initializing task StyleCopTask: The classes in the module cannot be loaded.
		 90 Warning(s)
		 1 Error(s)

**Comment by usr-sse2** [comment]
I have this too. I some StyleCop error earlier and I think that I solved it, but it's on a computer that I don't have access to now.

**Comment by marek-safar** [comment]
This fork is no longer maintained. Original Roslyn repo https://github.com/dotnet/roslyn now supports Mono build.
