### ISSUE TITLE
Can't compile roslyn with mono 3.12.1

### ISSUE THREAD

**Issue by buehler** [mono/roslyn#16]
Hey guys, I was trying to use the roslyn compiler (since we had a project using it)

and if I wan't to follow the steps you provided in the readme.md I get the following error at the first step (compile fakesign thingy)

XBuild Engine Version 12.0
Mono, Version 3.12.1.0
Copyright (C) 2005-2013 Various Mono authors

Build started 4/22/2015 3:46:30 PM.
__________________________________________________
src/Tools/Source/FakeSign/FakeSign.csproj: error : /home/cbuehler/Documents/Development/roslyn/src/Tools/Source/FakeSign/FakeSign.csproj: ../../../../build/VSL.Settings.Closed.targets: Project file could not be imported, it was being imported by /home/cbuehler/Documents/Development/roslyn/src/Tools/Source/FakeSign/FakeSign.csproj: Cannot cast from source type to destination type.
Build FAILED.
Errors:

src/Tools/Source/FakeSign/FakeSign.csproj: error : /home/cbuehler/Documents/Development/roslyn/src/Tools/Source/FakeSign/FakeSign.csproj: ../../../../build/VSL.Settings.Closed.targets: Project file could not be imported, it was being imported by /home/cbuehler/Documents/Development/roslyn/src/Tools/Source/FakeSign/FakeSign.csproj: Cannot cast from source type to destination type.

	 0 Warning(s)
	 1 Error(s)

Time Elapsed 00:00:00.0894550

any idea why?

Cheers
Chris

**Comment by DavidKarlas** [comment]
Maybe this can help :/
https://github.com/dotnet/roslyn/wiki/Linux-Instructions

**Comment by marek-safar** [comment]
Hi,

> Hey guys, I was trying to use the roslyn compiler (since we had a project
> using it)
>
> and if I wan't to follow the steps you provided in the readme.md I get
> the following error at the first step (compile fakesign thingy)
>
> XBuild Engine Version 12.0
>
That's the issue. Roslyn simply uses too many advanced msbuild features not
implemented or buggy in mono 3.12 xbuild. You need to use Mono 4.0 to build
roslyn.

Marek
