### ISSUE TITLE
build error with mono 904ca259cee7

### ISSUE THREAD

**Issue by kazzmir** [mono/roslyn#17]
I am using mono 904ca259cee75998f5fbaacbff9efeba0561ec8f (from July 17th, 2015) and am trying to build mono/roslyn 082fe91810c7ebc6e6ab70cf88177ec434e073c6 (from February 26, 2015) but receive a build error.

I did all the steps in the README first.

 $ xbuild src/Compilers/CSharp/csc/csc.csproj
    XBuild Engine Version 12.0
    Mono, Version 4.3.0.0
    Copyright (C) 2005-2013 Various Mono authors
    
    Build started 7/23/2015 5:17:05 PM.
    __________________________________________________
    Project "/home/jon/tmp/roslyn/src/Compilers/CSharp/csc/csc.csproj" (default target(s)):
    /home/jon/tmp/roslyn/src/Compilers/CSharp/csc/csc.csproj:  warning : Target 'CopyFilesToOutputDirectory', not found in the project
        Target PrepareForBuild:
            Configuration: Debug Platform: AnyCPU
        Target ResolveProjectReferences:
            Project "/home/jon/tmp/roslyn/src/Compilers/Core/Desktop/CodeAnalysis.Desktop.csproj" (default target(s)):
    /home/jon/tmp/roslyn/src/Compilers/Core/Desktop/CodeAnalysis.Desktop.csproj:  warning : Target 'CopyFilesToOutputDirectory', not found in the project
                Target PrepareForBuild:
                    Configuration: Debug Platform: AnyCPU
                Target ResolveProjectReferences:
                    Project "/home/jon/tmp/roslyn/src/Compilers/Core/Portable/CodeAnalysis.csproj" (default target(s)):
    /home/jon/tmp/roslyn/src/Compilers/Core/Portable/CodeAnalysis.csproj:  warning : Target 'CopyFilesToOutputDirectory', not found in the project
                        Target PrepareForBuild:
                            Configuration: Debug Platform: AnyCPU
                    Done building project "/home/jon/tmp/roslyn/src/Compilers/Core/Portable/CodeAnalysis.csproj".-- FAILED
                Task "MSBuild" execution -- FAILED
                Done building target "ResolveProjectReferences" in project "/home/jon/tmp/roslyn/src/Compilers/Core/Desktop/CodeAnalysis.Desktop.csproj".-- FAILED
            Done building project "/home/jon/tmp/roslyn/src/Compilers/Core/Desktop/CodeAnalysis.Desktop.csproj".-- FAILED
            Project "/home/jon/tmp/roslyn/src/Compilers/Core/Portable/CodeAnalysis.csproj" (default target(s)):
    /home/jon/tmp/roslyn/src/Compilers/Core/Portable/CodeAnalysis.csproj:  warning : Target 'CopyFilesToOutputDirectory', not found in the project
            Done building project "/home/jon/tmp/roslyn/src/Compilers/Core/Portable/CodeAnalysis.csproj".
            Project "/home/jon/tmp/roslyn/src/Compilers/CSharp/Desktop/CSharpCodeAnalysis.Desktop.csproj" (default target(s)):
    /home/jon/tmp/roslyn/src/Compilers/CSharp/Desktop/CSharpCodeAnalysis.Desktop.csproj:  warning : Target 'CopyFilesToOutputDirectory', not found in the project
                Target PrepareForBuild:
                    Configuration: Debug Platform: AnyCPU
                Target ResolveProjectReferences:
                    Project "/home/jon/tmp/roslyn/src/Compilers/Core/Desktop/CodeAnalysis.Desktop.csproj" (default target(s)):
    /home/jon/tmp/roslyn/src/Compilers/Core/Desktop/CodeAnalysis.Desktop.csproj:  warning : Target 'CopyFilesToOutputDirectory', not found in the project
                    Done building project "/home/jon/tmp/roslyn/src/Compilers/Core/Desktop/CodeAnalysis.Desktop.csproj".
                    Project "/home/jon/tmp/roslyn/src/Compilers/Core/Portable/CodeAnalysis.csproj" (default target(s)):
    /home/jon/tmp/roslyn/src/Compilers/Core/Portable/CodeAnalysis.csproj:  warning : Target 'CopyFilesToOutputDirectory', not found in the project
                    Done building project "/home/jon/tmp/roslyn/src/Compilers/Core/Portable/CodeAnalysis.csproj".
                    Project "/home/jon/tmp/roslyn/src/Compilers/CSharp/Portable/CSharpCodeAnalysis.csproj" (default target(s)):
    /home/jon/tmp/roslyn/src/Compilers/CSharp/Portable/CSharpCodeAnalysis.csproj:  warning : Target 'CopyFilesToOutputDirectory', not found in the project
                        Target PrepareForBuild:
                            Configuration: Debug Platform: AnyCPU
                        Target ResolveProjectReferences:
                            Project "/home/jon/tmp/roslyn/src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/CSharpSyntaxGenerator.csproj" (default target(s)):
    /home/jon/tmp/roslyn/src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/CSharpSyntaxGenerator.csproj:  warning : Target 'CopyFilesToOutputDirectory', not found in the project
                                Target PrepareForBuild:
                                    Configuration: Debug Platform: AnyCPU
                                Target GenerateSatelliteAssemblies:
                                No input files were specified for target GenerateSatelliteAssemblies, skipping.
                                Target GenerateSyntaxModel:
                                No output files were specified for target GenerateSyntaxModel, skipping.
                                Target GenerateSyntaxModelTests:
                                No output files were specified for target GenerateSyntaxModelTests, skipping.
                                Target GenerateBoundTree:
                                No output files were specified for target GenerateBoundTree, skipping.
                                Target GenerateErrorFacts:
                                No output files were specified for target GenerateErrorFacts, skipping.
                                Target GenerateTargetFrameworkMonikerAttribute:
                                Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
                                Target GenerateAssemblyInfoFile:
                                Skipping target "GenerateAssemblyInfoFile" because its outputs are up-to-date.
                                Target CoreCompile:
                                Skipping target "CoreCompile" because its outputs are up-to-date.
                                Target PostCompileBinaryModification:
                                Skipping target "PostCompileBinaryModification" because its outputs are up-to-date.
                            Done building project "/home/jon/tmp/roslyn/src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/CSharpSyntaxGenerator.csproj".
                            Project "/home/jon/tmp/roslyn/src/Tools/Source/CompilerGeneratorTools/Source/BoundTreeGenerator/CompilersBoundTreeGenerator.csproj" (default target(s)):
    /home/jon/tmp/roslyn/src/Tools/Source/CompilerGeneratorTools/Source/BoundTreeGenerator/CompilersBoundTreeGenerator.csproj:  warning : Target 'CopyFilesToOutputDirectory', not found in the project
                                Target PrepareForBuild:
                                    Configuration: Debug Platform: AnyCPU
                                Target GenerateSatelliteAssemblies:
                                No input files were specified for target GenerateSatelliteAssemblies, skipping.
                                Target GenerateSyntaxModel:
                                No output files were specified for target GenerateSyntaxModel, skipping.
                                Target GenerateSyntaxModelTests:
                                No output files were specified for target GenerateSyntaxModelTests, skipping.
                                Target GenerateBoundTree:
                                No output files were specified for target GenerateBoundTree, skipping.
                                Target GenerateErrorFacts:
                                No output files were specified for target GenerateErrorFacts, skipping.
                                Target GenerateTargetFrameworkMonikerAttribute:
                                Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
                                Target GenerateAssemblyInfoFile:
                                Skipping target "GenerateAssemblyInfoFile" because its outputs are up-to-date.
                                Target CoreCompile:
                                Skipping target "CoreCompile" because its outputs are up-to-date.
                                Target PostCompileBinaryModification:
                                Skipping target "PostCompileBinaryModification" because its outputs are up-to-date.
                                Target _CopyAppConfigFile:
                                Skipping target "_CopyAppConfigFile" because its outputs are up-to-date.
                            Done building project "/home/jon/tmp/roslyn/src/Tools/Source/CompilerGeneratorTools/Source/BoundTreeGenerator/CompilersBoundTreeGenerator.csproj".
                            Project "/home/jon/tmp/roslyn/src/Tools/Source/CompilerGeneratorTools/Source/CSharpErrorFactsGenerator/CSharpErrorFactsGenerator.csproj" (default target(s)):
    /home/jon/tmp/roslyn/src/Tools/Source/CompilerGeneratorTools/Source/CSharpErrorFactsGenerator/CSharpErrorFactsGenerator.csproj:  warning : Target 'CopyFilesToOutputDirectory', not found in the project
                                Target PrepareForBuild:
                                    Configuration: Debug Platform: AnyCPU
                                Target GenerateSatelliteAssemblies:
                                No input files were specified for target GenerateSatelliteAssemblies, skipping.
                                Target GenerateSyntaxModel:
                                No output files were specified for target GenerateSyntaxModel, skipping.
                                Target GenerateSyntaxModelTests:
                                No output files were specified for target GenerateSyntaxModelTests, skipping.
                                Target GenerateBoundTree:
                                No output files were specified for target GenerateBoundTree, skipping.
                                Target GenerateErrorFacts:
                                No output files were specified for target GenerateErrorFacts, skipping.
                                Target GenerateTargetFrameworkMonikerAttribute:
                                Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
                                Target GenerateAssemblyInfoFile:
                                Skipping target "GenerateAssemblyInfoFile" because its outputs are up-to-date.
                                Target CoreCompile:
                                Skipping target "CoreCompile" because its outputs are up-to-date.
                                Target PostCompileBinaryModification:
                                Skipping target "PostCompileBinaryModification" because its outputs are up-to-date.
                            Done building project "/home/jon/tmp/roslyn/src/Tools/Source/CompilerGeneratorTools/Source/CSharpErrorFactsGenerator/CSharpErrorFactsGenerator.csproj".
                            Project "/home/jon/tmp/roslyn/src/Compilers/Core/Portable/CodeAnalysis.csproj" (default target(s)):
    /home/jon/tmp/roslyn/src/Compilers/Core/Portable/CodeAnalysis.csproj:  warning : Target 'CopyFilesToOutputDirectory', not found in the project
                            Done building project "/home/jon/tmp/roslyn/src/Compilers/Core/Portable/CodeAnalysis.csproj".
                    Done building project "/home/jon/tmp/roslyn/src/Compilers/CSharp/Portable/CSharpCodeAnalysis.csproj".-- FAILED
                Task "MSBuild" execution -- FAILED
                Done building target "ResolveProjectReferences" in project "/home/jon/tmp/roslyn/src/Compilers/CSharp/Desktop/CSharpCodeAnalysis.Desktop.csproj".-- FAILED
            Done building project "/home/jon/tmp/roslyn/src/Compilers/CSharp/Desktop/CSharpCodeAnalysis.Desktop.csproj".-- FAILED
            Project "/home/jon/tmp/roslyn/src/Compilers/CSharp/Portable/CSharpCodeAnalysis.csproj" (default target(s)):
    /home/jon/tmp/roslyn/src/Compilers/CSharp/Portable/CSharpCodeAnalysis.csproj:  warning : Target 'CopyFilesToOutputDirectory', not found in the project
            Done building project "/home/jon/tmp/roslyn/src/Compilers/CSharp/Portable/CSharpCodeAnalysis.csproj".
        Task "MSBuild" execution -- FAILED
        Done building target "ResolveProjectReferences" in project "/home/jon/tmp/roslyn/src/Compilers/CSharp/csc/csc.csproj".-- FAILED
    Done building project "/home/jon/tmp/roslyn/src/Compilers/CSharp/csc/csc.csproj".-- FAILED
    
    Build FAILED.
    
    Warnings:
    
    /home/jon/tmp/roslyn/src/Compilers/CSharp/csc/csc.csproj (default targets) ->
    
        /home/jon/tmp/roslyn/src/Compilers/CSharp/csc/csc.csproj:  warning : Target 'CopyFilesToOutputDirectory', not found in the project
    
    /home/jon/tmp/roslyn/src/Compilers/CSharp/csc/csc.csproj (default targets) ->
    /home/jon/tmp/mono/install/lib/mono/4.5/Microsoft.Common.targets (ResolveProjectReferences target) ->
    /home/jon/tmp/roslyn/src/Compilers/Core/Desktop/CodeAnalysis.Desktop.csproj (default targets) ->
    
        /home/jon/tmp/roslyn/src/Compilers/Core/Desktop/CodeAnalysis.Desktop.csproj:  warning : Target 'CopyFilesToOutputDirectory', not found in the project
    
    /home/jon/tmp/roslyn/src/Compilers/CSharp/csc/csc.csproj (default targets) ->
    /home/jon/tmp/mono/install/lib/mono/4.5/Microsoft.Common.targets (ResolveProjectReferences target) ->
    /home/jon/tmp/roslyn/src/Compilers/Core/Desktop/CodeAnalysis.Desktop.csproj (default targets) ->
    /home/jon/tmp/mono/install/lib/mono/4.5/Microsoft.Common.targets (ResolveProjectReferences target) ->
    /home/jon/tmp/roslyn/src/Compilers/Core/Portable/CodeAnalysis.csproj (default targets) ->
    
        /home/jon/tmp/roslyn/src/Compilers/Core/Portable/CodeAnalysis.csproj:  warning : Target 'CopyFilesToOutputDirectory', not found in the project
    
    /home/jon/tmp/roslyn/src/Compilers/CSharp/csc/csc.csproj (default targets) ->
    /home/jon/tmp/mono/install/lib/mono/4.5/Microsoft.Common.targets (ResolveProjectReferences target) ->
    /home/jon/tmp/roslyn/src/Compilers/Core/Portable/CodeAnalysis.csproj (default targets) ->
    
        /home/jon/tmp/roslyn/src/Compilers/Core/Portable/CodeAnalysis.csproj:  warning : Target 'CopyFilesToOutputDirectory', not found in the project
    
    /home/jon/tmp/roslyn/src/Compilers/CSharp/csc/csc.csproj (default targets) ->
    /home/jon/tmp/mono/install/lib/mono/4.5/Microsoft.Common.targets (ResolveProjectReferences target) ->
    /home/jon/tmp/roslyn/src/Compilers/CSharp/Desktop/CSharpCodeAnalysis.Desktop.csproj (default targets) ->
    
        /home/jon/tmp/roslyn/src/Compilers/CSharp/Desktop/CSharpCodeAnalysis.Desktop.csproj:  warning : Target 'CopyFilesToOutputDirectory', not found in the project
    
    /home/jon/tmp/roslyn/src/Compilers/CSharp/csc/csc.csproj (default targets) ->
    /home/jon/tmp/mono/install/lib/mono/4.5/Microsoft.Common.targets (ResolveProjectReferences target) ->
    /home/jon/tmp/roslyn/src/Compilers/CSharp/Desktop/CSharpCodeAnalysis.Desktop.csproj (default targets) ->
    /home/jon/tmp/mono/install/lib/mono/4.5/Microsoft.Common.targets (ResolveProjectReferences target) ->
    /home/jon/tmp/roslyn/src/Compilers/Core/Desktop/CodeAnalysis.Desktop.csproj (default targets) ->
    
        /home/jon/tmp/roslyn/src/Compilers/Core/Desktop/CodeAnalysis.Desktop.csproj:  warning : Target 'CopyFilesToOutputDirectory', not found in the project
    
    /home/jon/tmp/roslyn/src/Compilers/CSharp/csc/csc.csproj (default targets) ->
    /home/jon/tmp/mono/install/lib/mono/4.5/Microsoft.Common.targets (ResolveProjectReferences target) ->
    /home/jon/tmp/roslyn/src/Compilers/CSharp/Desktop/CSharpCodeAnalysis.Desktop.csproj (default targets) ->
    /home/jon/tmp/mono/install/lib/mono/4.5/Microsoft.Common.targets (ResolveProjectReferences target) ->
    /home/jon/tmp/roslyn/src/Compilers/Core/Portable/CodeAnalysis.csproj (default targets) ->
    
        /home/jon/tmp/roslyn/src/Compilers/Core/Portable/CodeAnalysis.csproj:  warning : Target 'CopyFilesToOutputDirectory', not found in the project
    
    /home/jon/tmp/roslyn/src/Compilers/CSharp/csc/csc.csproj (default targets) ->
    /home/jon/tmp/mono/install/lib/mono/4.5/Microsoft.Common.targets (ResolveProjectReferences target) ->
    /home/jon/tmp/roslyn/src/Compilers/CSharp/Desktop/CSharpCodeAnalysis.Desktop.csproj (default targets) ->
    /home/jon/tmp/mono/install/lib/mono/4.5/Microsoft.Common.targets (ResolveProjectReferences target) ->
    /home/jon/tmp/roslyn/src/Compilers/CSharp/Portable/CSharpCodeAnalysis.csproj (default targets) ->
    
        /home/jon/tmp/roslyn/src/Compilers/CSharp/Portable/CSharpCodeAnalysis.csproj:  warning : Target 'CopyFilesToOutputDirectory', not found in the project
    
    /home/jon/tmp/roslyn/src/Compilers/CSharp/csc/csc.csproj (default targets) ->
    /home/jon/tmp/mono/install/lib/mono/4.5/Microsoft.Common.targets (ResolveProjectReferences target) ->
    /home/jon/tmp/roslyn/src/Compilers/CSharp/Desktop/CSharpCodeAnalysis.Desktop.csproj (default targets) ->
    /home/jon/tmp/mono/install/lib/mono/4.5/Microsoft.Common.targets (ResolveProjectReferences target) ->
    /home/jon/tmp/roslyn/src/Compilers/CSharp/Portable/CSharpCodeAnalysis.csproj (default targets) ->
    /home/jon/tmp/mono/install/lib/mono/4.5/Microsoft.Common.targets (ResolveProjectReferences target) ->
    /home/jon/tmp/roslyn/src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/CSharpSyntaxGenerator.csproj (default targets) ->
    
        /home/jon/tmp/roslyn/src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/CSharpSyntaxGenerator.csproj:  warning : Target 'CopyFilesToOutputDirectory', not found in the project
    
    /home/jon/tmp/roslyn/src/Compilers/CSharp/csc/csc.csproj (default targets) ->
    /home/jon/tmp/mono/install/lib/mono/4.5/Microsoft.Common.targets (ResolveProjectReferences target) ->
    /home/jon/tmp/roslyn/src/Compilers/CSharp/Desktop/CSharpCodeAnalysis.Desktop.csproj (default targets) ->
    /home/jon/tmp/mono/install/lib/mono/4.5/Microsoft.Common.targets (ResolveProjectReferences target) ->
    /home/jon/tmp/roslyn/src/Compilers/CSharp/Portable/CSharpCodeAnalysis.csproj (default targets) ->
    /home/jon/tmp/mono/install/lib/mono/4.5/Microsoft.Common.targets (ResolveProjectReferences target) ->
    /home/jon/tmp/roslyn/src/Tools/Source/CompilerGeneratorTools/Source/BoundTreeGenerator/CompilersBoundTreeGenerator.csproj (default targets) ->
    
        /home/jon/tmp/roslyn/src/Tools/Source/CompilerGeneratorTools/Source/BoundTreeGenerator/CompilersBoundTreeGenerator.csproj:  warning : Target 'CopyFilesToOutputDirectory', not found in the project
    
    /home/jon/tmp/roslyn/src/Compilers/CSharp/csc/csc.csproj (default targets) ->
    /home/jon/tmp/mono/install/lib/mono/4.5/Microsoft.Common.targets (ResolveProjectReferences target) ->
    /home/jon/tmp/roslyn/src/Compilers/CSharp/Desktop/CSharpCodeAnalysis.Desktop.csproj (default targets) ->
    /home/jon/tmp/mono/install/lib/mono/4.5/Microsoft.Common.targets (ResolveProjectReferences target) ->
    /home/jon/tmp/roslyn/src/Compilers/CSharp/Portable/CSharpCodeAnalysis.csproj (default targets) ->
    /home/jon/tmp/mono/install/lib/mono/4.5/Microsoft.Common.targets (ResolveProjectReferences target) ->
    /home/jon/tmp/roslyn/src/Tools/Source/CompilerGeneratorTools/Source/CSharpErrorFactsGenerator/CSharpErrorFactsGenerator.csproj (default targets) ->
    
        /home/jon/tmp/roslyn/src/Tools/Source/CompilerGeneratorTools/Source/CSharpErrorFactsGenerator/CSharpErrorFactsGenerator.csproj:  warning : Target 'CopyFilesToOutputDirectory', not found in the project
    
    /home/jon/tmp/roslyn/src/Compilers/CSharp/csc/csc.csproj (default targets) ->
    /home/jon/tmp/mono/install/lib/mono/4.5/Microsoft.Common.targets (ResolveProjectReferences target) ->
    /home/jon/tmp/roslyn/src/Compilers/CSharp/Desktop/CSharpCodeAnalysis.Desktop.csproj (default targets) ->
    /home/jon/tmp/mono/install/lib/mono/4.5/Microsoft.Common.targets (ResolveProjectReferences target) ->
    /home/jon/tmp/roslyn/src/Compilers/CSharp/Portable/CSharpCodeAnalysis.csproj (default targets) ->
    /home/jon/tmp/mono/install/lib/mono/4.5/Microsoft.Common.targets (ResolveProjectReferences target) ->
    /home/jon/tmp/roslyn/src/Compilers/Core/Portable/CodeAnalysis.csproj (default targets) ->
    
        /home/jon/tmp/roslyn/src/Compilers/Core/Portable/CodeAnalysis.csproj:  warning : Target 'CopyFilesToOutputDirectory', not found in the project
    
    /home/jon/tmp/roslyn/src/Compilers/CSharp/csc/csc.csproj (default targets) ->
    /home/jon/tmp/mono/install/lib/mono/4.5/Microsoft.Common.targets (ResolveProjectReferences target) ->
    /home/jon/tmp/roslyn/src/Compilers/CSharp/Portable/CSharpCodeAnalysis.csproj (default targets) ->
    
        /home/jon/tmp/roslyn/src/Compilers/CSharp/Portable/CSharpCodeAnalysis.csproj:  warning : Target 'CopyFilesToOutputDirectory', not found in the project
    
         13 Warning(s)
         0 Error(s)
    
    Time Elapsed 00:00:03.9097040

**Comment by marek-safar** [comment]
This fork is no longer maintained. Original Roslyn repo https://github.com/dotnet/roslyn now supports Mono build.
