### ISSUE TITLE
PCL instructions

### ISSUE THREAD

**Issue by tomkcook** [mono/roslyn#18]
Are the instructions for installing PCL in README.md right?  I don't have a /usr/lib/mono/xbuild-frameworks/.NETPortable but I do have a /usr/lib/mono/xbuild-frameworks/.NETFramework.

I'm using mono 4.2.1, which I believe equates to the commit referenced in README.md.

**Comment by marek-safar** [comment]
This fork is no longer maintained. Original Roslyn repo https://github.com/dotnet/roslyn now supports Mono build.
