### ISSUE TITLE
System.IO.MemoryMappedFiles and EncodedStringText class don't compile with Mono

### ISSUE THREAD

**Issue by sergey-litvinov** [mono/roslyn#2]
Hey guys,

The latest sources don't compile. The issue is in [EncodedStringText](https://github.com/mono/roslyn/blob/0a414591d427e3c624eb6b6059575fb7db15357a/Src/Compilers/Core/Desktop/EncodedStringText.cs) class. It uses `MemoryMappedViewStream.SafeMemoryMappedViewHandle` property that isn't available in Mono at the moment. Here is a [link to Mono's implementation](https://github.com/mono/mono/blob/master/mcs/class/System.Core/System.IO.MemoryMappedFiles/MemoryMappedFile.cs). Currently it has `[MonoTODO]` attribute, and it causes issues during build.

Seems like it is used just for perfomance puproses, so if I comment block that uses MemoryMappedViewStream, then it works fine.

I'm not sure how you usually handle such things, but just wanted to inform you about this compilation issue.
I've used the latest Mono compiled from the master branch.

**Comment by marek-safar** [comment]
This fork is no longer maintained. Original Roslyn repo https://github.com/dotnet/roslyn now supports Mono build.
