### ISSUE TITLE
Build fails under Mono 4.2.1 - structs have parameterless constructors

### ISSUE THREAD

**Issue by tomkcook** [mono/roslyn#20]
Building Roslyn with Mono 4.2.1, I get the following error:

```
Emit/EditAndContinue/EncHoistedLocalInfo.cs(16,16): error CS0568: Structs cannot contain explicit parameterless constructors
```

I gather that parameterless constructors have been introduced in C# 6.  AFAICT, mcs version 4.2.1 is considerably later than commit 673e8fa8eedc27d8f92792b7247b2fc121490b30 - does README.md need to be updated?

**Comment by tomkcook** [comment]
And have confirmed that this is still a problem with mono `8269971fd1901aa3771a0d0198ffd39672779452`, current as of the end of last week.

**Comment by marek-safar** [comment]
This fork is no longer maintained. Original Roslyn repo https://github.com/dotnet/roslyn now supports Mono build.
