### ISSUE TITLE
Build instructions do not work with mono 074873ab99fa14c3407d2563f833573ec796d7d7

### ISSUE THREAD

**Issue by josephrdean** [mono/roslyn#5]
The instructions state to build/install mono hash 73bb10fff3d7b828c3508c4ab34126baa8345bd9 or newer. I followed the instructions I think exactly and I get this error when compiling csc:

Emit/EditAndContinue/EncHoistedLocalInfo.cs(16,16): error CS0568: Structs cannot contain explicit parameterless constructors

I changed EncHoistedLocalInfo from a struct to a class to get past this compiler error and csc now successfully builds for me. Perhaps changes to mono between 0748  and 73bb now correctly enforce the limitation that structs may not contain explicit parameterless constructors as per http://msdn.microsoft.com/en-us/library/aa288208%28v=vs.71%29.aspx ?

**Comment by gusennan** [comment]
+1

**Comment by marek-safar** [comment]
Hello,

> The instructions state to build/install mono hash
> 73bb10fff3d7b828c3508c4ab34126baa8345bd9 or newer. I followed the
> instructions I think exactly and I get this error when compiling csc:
>
The hash has been updated and it builds fine for me.

Thanks
Marek

**Comment by grbd** [comment]
I just ran into the same problem above, I'm using a Raspberry pi2 (gentoo) with mono 4.2.2.29
In order to get csc.exe to compile from this repo I had to make the same change for a struct to a class

**Comment by marek-safar** [comment]
This fork is no longer maintained. Original Roslyn repo https://github.com/dotnet/roslyn now supports Mono build.
