### ISSUE TITLE
Can't build with csc.exe

### ISSUE THREAD

**Issue by Fabi** [mono/roslyn#6]
Hey,

I just compiled roslyn on Debian wheezy and got the csc.exe....

I tried to build a simple test.cs file but I just can't get it working:

root@xx:/usr/local/lib/mono/4.5# mono csc.exe /out:test.exe test.cs
Microsoft (R) Visual C# Compiler version 1.0.0.0
Copyright (C) Microsoft Corporation. All rights reserved.

error CS0006: Metadata file 'System.Windows.Forms.Dll' could not be found

**Comment by DavidKarlas** [comment]
I'm not expert in this area... but shouldn't you add "/r:/usr/local/lib/mono/4.5/System.Windows.Forms.dll"?
Btw.. In case you will use full paths instead of relative you might want to cherrypick this commit: https://github.com/DavidKarlas/roslyn/commit/5b2715280d868ce69e73779c33a2ea653ad715bc

**Comment by DavidKarlas** [comment]
Assuming test.cs is using "System.Windows.Forms.dll"...

**Comment by Fabi** [comment]
using System;

 namespace ConsoleApplication4
 {
     class Program
     {
         static void Main(string[] args)
         {
             Console.WriteLine("\{Console.ReadLine()}");
             Console.ReadKey();
         }
     }
 }

**Comment by Fabi** [comment]
Ah I just saw, that it searches for "System.Windows.Forms.Dll' and not "System.Windows.Forms.dll'

copy the dll to Dll seems to work. But I wonder if the current csc.exe is able to compile new roslyn features

**Comment by Fabi** [comment]
Ok I noticed that the new interpolated syntax with the $ is already used.
